name: Python Lint

on: [push, pull_request]

jobs:
  lint:
    defaults:
      run:
        working-directory: .

    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
        platform: [ubuntu-22.04]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r dev-requirements.txt
          python3 -m pip install --upgrade build
          pip install -e .
      - name: Lint with flake8
        run: |
          make flake8
      - name: Lint with pylint
        run: |
          make pylint
